# DECISION TREE

In [1]:
# NAME   : ARPAN KHARE
# CLASS  : CS 3RD YEAR
# En.ro  : 047

In [28]:
import pandas as pd
import numpy as np

In [29]:
data=pd.read_csv("Iris.csv")

In [30]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [31]:
from sklearn.preprocessing import LabelEncoder

In [32]:
data['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [33]:
from sklearn import preprocessing
Ps2=preprocessing.LabelEncoder()

In [34]:
data['Species']=Ps2.fit_transform(data['Species'])

In [35]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [36]:
data.head(103)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
98    99            5.1           2.5            3.0           1.1        1
99   100            5.7           2.8            4.1           1.3        1
100  101            6.3           3.3            6.0           2.5        2
101  102            5.8           2.7            5.1           1.9        2
102  103            7.1           3.0            5.9           2.1        2

[103 rows x 6 columns]

In [37]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression

In [38]:
iris=load_iris()
X=iris.data
Y=iris.target

In [39]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y, test_size=0.2,random_state=42)


In [40]:
clf = DecisionTreeClassifier()

In [41]:
clf=clf.fit(X_train,Y_train)

In [42]:
Y_pred = clf.predict(X_test)

In [43]:
accuracy=accuracy_score(Y_test,Y_pred)
print("Accuracy :",accuracy)

Accuracy : 1.0


In [44]:
mode =LinearRegression()
mymode=mode.fit(X_train,Y_train)

In [45]:
# k fold  cv
#importing cross _val_score function
from sklearn.model_selection import cross_val_score

In [46]:
#5 fold cross valiation
scores = cross_val_score(mymode,X_train,Y_train,scoring='r2', cv=5)
scores

array([0.9200928 , 0.94124878, 0.89580762, 0.89060451, 0.91120692])

In [47]:
#printing the average score of testing and prediction accuracy    
print(np.mean(scores))

0.911792126690884


In [54]:
# importing the scores on the test dataset
# First : Prediction
# impporting cross_val_predict function
from sklearn.model_selection import cross_val_predict
# the prediction
pred =cross_val_predict(mode,X_test,Y_test)
pred

array([ 1.15461659,  0.06999107,  2.2527562 ,  1.33514986,  1.30149647,
        0.10205409,  1.05065976,  1.9638442 ,  1.29677309,  0.99673419,
        1.74251584, -0.14438054, -0.18049928, -0.18191799,  0.10463817,
        1.48472475,  2.10223218,  0.86476941,  1.13826677,  1.93183395,
       -0.01432887,  1.56287488,  0.13163122,  1.85565254,  1.61228742,
        2.04932808,  1.5197717 ,  2.07505373,  0.07149073, -0.02065033])

In [56]:
#5 FOLD CROSS VALIDATION ON TEST DATA
scores_test=cross_val_score(mode,X_test,Y_test,cv=5)
scores

array([0.9200928 , 0.94124878, 0.89580762, 0.89060451, 0.91120692])

In [57]:
# the average mean score 
print(np.mean(scores))

0.911792126690884
